# Generated by Django 5.2.6 on 2025-09-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories'), ('shoes', 'Shoes'), ('skills', 'Skills'), ('superDuperUltraRareUnique Item', 'SuperDuperUltraRareUnique Item')], max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
